name: Medium Auto Poster

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Dependencies
        run: pip install selenium feedparser webdriver-manager selenium-stealth

      # --- هنا التغيير: نمرر كلا الكوكيين ---
      - name: Run Python Script
        id: script
        env:
          MEDIUM_SID_COOKIE: ${{ secrets.MEDIUM_SID_COOKIE }}
          MEDIUM_UID_COOKIE: ${{ secrets.MEDIUM_UID_COOKIE }}
        run: python main.py
        
      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            *.png
            *.html
